- name: Instalez NGINX
  hosts: all
  become: true  # tot ce e mai jos ruleaza cu SUDO !!!!!!!!!!!!!!!!!!!!!!!!
  tasks:
    - name: Actualizez lista de pachete
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Instalez nginx
      apt:
        name: nginx
        state: latest

    - name: Ma asigur ca a pornit NGINX
      service:
        name: nginx
        state: started
        enabled: yes